AWSTemplateFormatVersion: 2010-09-09
Description: VPC for ECS
Resources:
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
    
  subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Sub 10.0.0.0/24
      MapPublicIpOnLaunch: true

  subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Sub 10.0.2.0/24
      MapPublicIpOnLaunch: true
    
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    
  VPCGatewayAttachment:  
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC
      
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPC
  
  RouteTableAssociation1:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref subnet1
      RouteTableId: !Ref RouteTable
      
  RouteTableAssociation2:
     Type: AWS::EC2::SubnetRouteTableAssociation
     Properties:
       SubnetId: !Ref subnet2
       RouteTableId: !Ref RouteTable
       
  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      GatewayId: !Ref InternetGateway
      RouteTableId: !Ref RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      
Outputs:
  VPC:
    Description: VPC
    Value: !Ref VPC
    Export:
      Name: VPC
    
  subnet1:
    Description: subnet1
    Value: !Ref subnet1
    Export:
      Name: subnet1
  
  subnet2:
    Description: subnet2
    Value: !Ref subnet2
    Export:
      Name: subnet2
        