AWSTemplateFormatVersion: 2010-09-09
Description: VPC for ECS
Resources:
VPC:
  Type: AWS::EC2::VPC
  Properties:
    CidrBlock: 10.0.0.0/16
    EnableDnsSupport: true
    EnableDnsHostnames: true
    InstanceTenancy: default
    
subnet1:
  Type: AWS::EC2::Subnet
  VpcId: !Ref VPC
  AvailabilityZone: !Select [0, !GetAZs '']
  CidrBlick: !Sub 10.0.1.0/24
  MapPublicIpOnLaunch: true

subnet2:
  Type: AWS::EC2::Subnet
  VpcId: !Ref VPC
  AvailabilityZone: !Select [1, !GetAZs '']
  CidrBlick: !Sub 10.0.2.0/24
  MapPublicIpOnLaunch: true
  
InternetGateway:
  Type: AWS::EC2::InternetGateway
  
VPCGatewayAttachment:  
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
    InternetGatewayId: !Ref InternetGateway
    VpcId: !Ref VPC
    
RouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
    VpcId: !Ref VPC

RouteTableAssociation1:
  Type: AWS::EC2::RouteTableAssociation
  Properties:
    SubnetId: !Ref Subnet1
    RouteTableId: !Ref RouteTable
    
RouteTableAssociation2:
   Type: AWS::EC2::RouteTableAssociation
   Properties:
     SubnetId: !Ref Subnet2
     RouteTableId: !Ref RouteTable
     
InternetRoute:
  Type: AWS::EC2::Route
  DependsOn: VPCGatewayAttachment
  Properties:
    GatewayId: !Ref VPCGatewayAttachment
    RouteTableId: !Ref RouteTable
    DestinationCidrBlock: 0.0.0.0/0
    
Output:
  VPC:
    Description: VPC
    Value: !Ref VPC
    Export:
      Name: VPC
  
  Subnet1:
    Description: Subnet1
    Value: !Ref Subnet1
    Export:
      Name: Subnet1
  
  Subnet2:
    Description: Subnet1
    Value: !Ref Subnet2
    Export:
      Name: Subnet2
      